In [73]:
import pandas as pd 

football_players = pd.read_csv('football_players.csv')

football_games = pd.read_csv('football_games.csv')

In [75]:
len(football_players)

319875

In [33]:
f_games = '''Wk = models.IntegerField()
Day = models.CharField(max_length=255)
Date = models.DateField()
Time = models.TimeField()
Home = models.CharField(max_length=255)
Away = models.CharField(max_length=255)
xG = models.FloatField()
xG_1 = models.FloatField()
Score = models.CharField(max_length=255)
season = models.CharField(max_length=255)
game_id = models.IntegerField()'''.split('\n')

game_cols = [i.split('=')[0].strip() for i in f_games]

for g_c in game_cols:
    if g_c not in football_games.columns:
        print(g_c)

xG_1

In [34]:
f_players = '''index = models.IntegerField()
Player = models.CharField(max_length=255)
number = models.IntegerField()
Nation = models.CharField(max_length=255)
Pos = models.CharField(max_length=255)
Age = models.FloatField()
Min = models.IntegerField()
Gls = models.IntegerField()
Ast = models.IntegerField()
PK = models.IntegerField()
PKatt = models.IntegerField()
Sh = models.IntegerField()
SoT = models.IntegerField()
CrdY = models.IntegerField()
CrdR = models.IntegerField()
Touches = models.IntegerField()
Tkl = models.IntegerField()
Int = models.IntegerField()
Blocks = models.IntegerField()
xG = models.FloatField()
npxG = models.FloatField()
xAG = models.FloatField()
SCA = models.IntegerField()
GCA = models.IntegerField()
Cmp_x = models.FloatField()
Att_x = models.FloatField()
Cmp_pct_x = models.FloatField()
PrgP = models.IntegerField()
Carries = models.IntegerField()
PrgC = models.IntegerField()
Att_x_alt = models.FloatField()
Succ = models.FloatField()
SoTA = models.FloatField()
GA = models.FloatField()
Saves = models.FloatField()
Save_pct = models.FloatField()
PSxG = models.FloatField()
Cmp_y = models.FloatField()
Att_y = models.FloatField()
Cmp_pct_y = models.FloatField()
Att_GK = models.FloatField()
Thr = models.FloatField()
Launch_pct = models.FloatField()
AvgLen = models.FloatField()
Opp = models.FloatField()
Stp = models.FloatField()
Stp_pct = models.FloatField()
OPA = models.IntegerField()
AvgDist = models.FloatField()
home = models.CharField(max_length=255)
game_id = models.IntegerField()'''.split('\n')

player_cols = [i.split('=')[0].strip() for i in f_players]

for p_c in player_cols:
    if p_c not in football_players.columns:
        print(p_c)

number
Cmp_pct_x
Att_x_alt
Save_pct
Cmp_pct_y
Att_GK
Launch_pct
Stp_pct
OPA

In [14]:
football_players.head()

,index,Player,#,Nation,Pos,Age,Min,Gls,Ast,PK,...,Stp,Stp%,#OPA,AvgDist,home,game_id,Cmp,Att,Cmp%,Att.1
0,0,15 Players,NaN,NaN,NaN,NaN,990.0,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,1,0,NaN,NaN,NaN,NaN
1,1,Alassane Pléa,14.0,fr FRA,FW,28-156,63.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,1,0,NaN,NaN,NaN,NaN
2,2,Christoph Kramer,6.0,de GER,DM,30-175,90.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,1,0,NaN,NaN,NaN,NaN
3,3,Florian Neuhaus,32.0,de GER,DM,24-150,89.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,1,0,NaN,NaN,NaN,NaN
4,4,Hannes Wolf,11.0,at AUT,LW,22-119,71.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,1,0,NaN,NaN,NaN,NaN

In [15]:
football_games

,Wk,Day,Date,Time,Home,Away,Score,xG,xG.1,season,game_id
0,1.0,Fri,2023-08-18,20:30,Werder Bremen,Bayern Munich,0â4,0.6,2.8,2023-2024,0.0
1,1.0,Sat,2023-08-19,15:30,Leverkusen,RB Leipzig,3â2,1.4,1.6,2023-2024,1.0
2,1.0,Sat,2023-08-19,15:30,Wolfsburg,Heidenheim,2â0,2.2,1.2,2023-2024,2.0
3,1.0,Sat,2023-08-19,15:30,Stuttgart,Bochum,5â0,3.0,0.8,2023-2024,3.0
4,1.0,Sat,2023-08-19,15:30,Augsburg,Gladbach,4â4,2.3,1.7,2023-2024,4.0
...,...,...,...,...,...,...,...,...,...,...,...
16541,38.0,Sun,2020-08-02,18:00,SPAL,Fiorentina,1â3,0.5,2.3,2019-2020,416.0
16542,38.0,Sun,2020-08-02,20:45,Genoa,Hellas Verona,3â0,0.8,1.1,2019-2020,417.0
16543,38.0,Sun,2020-08-02,20:45,Sassuolo,Udinese,0â1,1.3,1.7,2019-2020,418.0
16544,38.0,Sun,2020-08-02,20:45,Bologna,Torino,1â1,0.9,1.9,2019-2020,419.0
16545,38.0,Sun,2020-08-02,20:45,Lecce,Parma,3â4,2.7,3.2,2019-2020,420.0

In [9]:
football_games.head()

,Unnamed: 0.1,Unnamed: 0,Wk,Day,Date,Time,Home,Away,Score,xG,xG.1,season,game_id
0,0,0,1.0,Fri,2023-08-18,20:30,Werder Bremen,Bayern Munich,0â4,0.6,2.8,2023-2024,0.0
1,1,1,1.0,Sat,2023-08-19,15:30,Leverkusen,RB Leipzig,3â2,1.4,1.6,2023-2024,1.0
2,2,2,1.0,Sat,2023-08-19,15:30,Wolfsburg,Heidenheim,2â0,2.2,1.2,2023-2024,2.0
3,3,3,1.0,Sat,2023-08-19,15:30,Stuttgart,Bochum,5â0,3.0,0.8,2023-2024,3.0
4,4,4,1.0,Sat,2023-08-19,15:30,Augsburg,Gladbach,4â4,2.3,1.7,2023-2024,4.0